### ISSUE TITLE
[3.0 + IE10] Banner block does not constrain its contents

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#104]
**Starter 3.0.x-dev on IE10**

![image](https://user-images.githubusercontent.com/5170590/56934399-e2946b00-6b3f-11e9-8707-180c9e2def5b.png)

Looks like this on IE11:

![image](https://user-images.githubusercontent.com/5170590/56934414-f63fd180-6b3f-11e9-8882-9e57cdfe8951.png)

**Comment by Cheddam** [comment]
This will be broken in a different way when #127 is merged:

![image](https://user-images.githubusercontent.com/242621/57050439-a5131780-6cd0-11e9-8e8c-0e46827cb94a.png)

**Comment by robbieaverill** [comment]
Resolved in https://github.com/silverstripe/cwp-starter-theme/pull/130 for starter and https://github.com/silverstripe/cwp-watea-theme/pull/49 for Wātea
