### ISSUE TITLE
Blog template without sidebar should be offset

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#108]
**Starter 3.0.x-dev**

![image](https://user-images.githubusercontent.com/5170590/56936800-5c7f2100-6b4d-11e9-8124-8468ffbbad6c.png)

When there's no sidebar, the layout should be offset so it displays centered.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/cwp-starter-theme/pull/109

**Comment by ScopeyNZ** [comment]
#109 is merged
