### ISSUE TITLE
[3.0 + IE10] Bootstrap form validation state icons are positioned incorrectly

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#110]
**Starter 3.0.x-dev with IE10**

![image](https://user-images.githubusercontent.com/5170590/56937095-0a3eff80-6b4f-11e9-89c2-ce841825ce6b.png)

On IE11 it looks like this:

![image](https://user-images.githubusercontent.com/5170590/56937116-20e55680-6b4f-11e9-9c4b-38274eb20842.png)

**Comment by Cheddam** [comment]
Weirdly, this is a Bootstrap bug:

![image](https://user-images.githubusercontent.com/242621/56940427-83941d80-6b62-11e9-8cfd-077f02facaca.png)
