### ISSUE TITLE
[3.0 + IE10/11] Button padding is not consistent on each side

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#111]
**Version: 3.0.x-dev with IE10/11**

![image](https://user-images.githubusercontent.com/5170590/56937169-6ace3c80-6b4f-11e9-9c21-16e3183227d3.png)
![image](https://user-images.githubusercontent.com/5170590/56937171-6dc92d00-6b4f-11e9-8099-5821524df3b7.png)

It looks like this on Chrome:

![image](https://user-images.githubusercontent.com/5170590/56937199-8df8ec00-6b4f-11e9-8e9d-e2682ea7edb7.png)
![image](https://user-images.githubusercontent.com/5170590/56937201-92250980-6b4f-11e9-9dbb-6a2be587701c.png)

It looks like it's out by 2-3 pixels on the bottom.

**Comment by Cheddam** [comment]
Both are issues with Bootstrap:

![image](https://user-images.githubusercontent.com/242621/56940873-22ba1480-6b65-11e9-9ee8-5176aed1dd04.png)

![image](https://user-images.githubusercontent.com/242621/56940908-55fca380-6b65-11e9-8000-2d875c05e0ff.png)
