### ISSUE TITLE
Aside must not be contained in another landmark

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#116]
All starter theme versions.

Axe report:

>Aside must not be contained in another landmark. Ensures the complementary landmark or aside is at top level. [Fix the following:] The complementary landmark is contained in another landmark.
>Element location
> `.footer-social-links`
> Element source
> `<div class="footer-nav-links footer-social-links col-auto" role="complementary">`

**Comment by Cheddam** [comment]
Resolved in #146.
