### ISSUE TITLE
Main landmark must not be contained in another landmark (in blog pages)

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#117]
**Starter 3.0.x-dev**

> Main landmark must not be contained in another landmark
> 
> Issue description: Ensures the main landmark is at top level
> 
> Impact: moderate
> 
> Element location: `.blog-main`
> Element source: `<div class="blog-main" role="main">`
> 
> To solve this violation, you need to fix the following:
> The main landmark is contained in another landmark.

Matching second issue from the Axe checker:

> Issue description: Ensures the document has only one main landmark and each iframe in the page has at most one main landmark
> 
> Impact: moderate
> 
> Element location: `html`
> Element source: `<html class="no-js" lang="en-NZ">`
> To solve this violation, you need to fix the following: Document has more than one main landmark
> 
> Related nodes: `#main`, `.blog-main`

**Comment by Cheddam** [comment]
Fixed in #147.
