### ISSUE TITLE
Force HTTPS for CDN request in frontend template

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/cwp-starter-theme#172]
We've currently not enforcing that sites with this module access the following CDN over HTTPS, which apparently could be as simple as appending  'https' to the link, here:

https://github.com/silverstripe/cwp-starter-theme/blob/0fdf8ba16ff45c0559872fc88e90713f42439ae3/templates/Page.ss#L26

Uncovered this while running a browser security checker tool, message: `Subresource Integrity (SRI) not implemented, and external scripts are loaded over HTTP or use protocol-relative URLs via src="//..."`

See guidance from Mozilla: https://infosec.mozilla.org/guidelines/web_security#resource-loading

**Comment by brynwhyman** [comment]
Raised the same issue for the watea theme: https://github.com/silverstripe/cwp-watea-theme/issues/114

**Comment by emteknetnz** [comment]
The PR for this request was merged
