### ISSUE TITLE
Switch from Laravel Mix to use Webpack

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#25]
To follow in line with SilverStripe 4 modules, we could perhaps switch this and the Wātea theme to use Webpack directly (possibly with the silverstripe/webpack-config module too) instead of using the Laravel Mix wrapper around it.

Up for discussion - Laravel Mix _is_ pretty easy to use, so maybe it's not worth it.

**Comment by robbieaverill** [comment]
After reading this again it might be best to keep it. The most important thing for this theme is that it follows the practice of what we'd encourage projects to use, in which case Laravel Mix is common (while we use Webpack for SilverStripe _modules_). cc @chillu

**Comment by chillu** [comment]
Yeah, I think that's pretty low value - there's more driver for using something that's common for frontend devs than to use the same stack as core. Closing
