### ISSUE TITLE
Required fields are no longer alerting to the eye

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-starter-theme#27]
Form fields with (validation) errors on them highlight with a red border and error message in the SilverStripe 3.x compatible versions.

In the SilverStripe 4.x release line however the red is gone (both text and input border), and the error messages blend in with the background and are easily missed.

Old (screenshot from CWP 1.8 install):
![image](https://user-images.githubusercontent.com/778003/37061352-1c600bce-21f8-11e8-9159-1a38052bef9f.png)

**Comment by robbieaverill** [comment]
Looks like the jQuery validate plugin that ships with both userforms and comments isn't being enabled. The resource is added and is loaded after jQuery but before anything else, so that's OK - just not applying it correctly.

**Comment by raissanorth** [comment]
@dylan It appears that this issue has been fixed. Using

```
cwp/starter-theme                                        2.0.x-dev 68ab6d5 CWP Theme
silverstripe/framework                                   4.x-dev 373a8af   The SilverStripe framework
```

the required fields are well highlighted. 

------------

Before form submission:

![image](https://user-images.githubusercontent.com/14869519/45188901-7e5c2880-b28a-11e8-9c16-10782bb6c828.png)

After submission:

![image](https://user-images.githubusercontent.com/14869519/45188896-756b5700-b28a-11e8-9633-d975b1c74d6c.png)
