### ISSUE TITLE
Footer breaks when there are only social links

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#3]
When the footer only has social links and no 'Footer Holder' with pages the footer breaks (see below).

![image](https://user-images.githubusercontent.com/5170590/32258004-2693a9b8-bf1d-11e7-9ba6-86c4efe10ccb.png)

(Migrated from [GitLab](https://gitlab.cwp.govt.nz/cwp/starter-theme/issues/6) cc @sachajudd)

**Comment by maxime-rainville** [comment]
Couldn't replicate in the latest version of Watea.
