### ISSUE TITLE
Remove "Category icon" drop-down field

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/cwp-starter-theme#46]
In the "Home" page type, under the "Features" tab, the "Category icon" drop-down field does not work and should be removed as it is not required in the themes.

Note: This is only an issue in the Starter theme, not Watea. 

CMS-
![image](https://user-images.githubusercontent.com/24258161/40820167-06df3852-65b3-11e8-9ffd-9adfe062687e.png)

Output-
![image](https://user-images.githubusercontent.com/24258161/40820162-ffe79468-65b2-11e8-860a-27722c74ef30.png)

cc @clarkepaul

**Comment by robbieaverill** [comment]
The time has gone to be able to do this in CWP 2.0 since it would break the public API. We can hide it though, if you'd like

**Comment by sachajudd** [comment]
In that case, if we can hide it that would be great. It would be good to keep in mind when we can remove it completely.

**Comment by robbieaverill** [comment]
Cool, I guess we'd need to make it configurable so that anyone who does want them can re-enable them with configuration

**Comment by brynwhyman** [comment]
Maybe a silly question, but what's the reasoning for removing this functionality as opposed to fixing it so the category icons _do_ work?

**Comment by robbieaverill** [comment]
@brynwhyman the icons in the list are old, we use FontAwesome icons since the starter and Wātea themes have been created. Due to the the fact that [enums are not extensible](https://github.com/silverstripe/silverstripe-framework/issues/8401) we can't easily make the list dynamic, so we "removed" it instead.

**Comment by maxime-rainville** [comment]
Not worth doing.
