### ISSUE TITLE
Elemental Banner Block template not applying

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/cwp-starter-theme#51]
With CWP 2.1.0-beta1 it includes the new elemental block modules:

silverstripe/elemental-bannerblock
silverstripe/elemental-fileblock

This means the custom template for banner blocks is not being applied in 2.1.0

The directory names need to be updated (namespacing) but should we create a copy or rename the existing and add composer constraints? If constraints, which ones? The elemental modules are not required as part of `cwp/installer` but they are part of kitchen sink...

Note that it looks fine without the template, the template just adds some accessibility attributes.

**Comment by robbieaverill** [comment]
I think the safest option is to leave the old templates where they are and copy them to new ones that have the new namespaced filenames. We can add a comment to the old ones to mark them as deprecated, and probably release a new starter theme minor version that has the ^4.2 constraint on core.

Thoughts?

**Comment by ScopeyNZ** [comment]
I'm happy with that. I'm still not sure if there's a "good" answer for the constraint. Technically the existing elemental blocks module can be installed on 4.2, there's no invalid dependencies there. 4.2 doesn't really mean anything. I would say that having `cwp/cwp: ^2.1` makes more sense because it's most likely they've used a 2.1.0 recipe or something. But again, there's no guarantee.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/cwp-starter-theme/pull/66
