### ISSUE TITLE
wrong scss files referenced in inspector

### ISSUE THREAD

**Issue by LABCAT** [silverstripe/cwp-starter-theme#52]
Not sure if this is related to the theme or laravel mix.

When inspecting elements in chrome the styles tab will display the styles for an element with a link to the scss file where these styles are located. However these references are completely wrong.

For example when I inspect the HTML element:
![image](https://user-images.githubusercontent.com/9105153/42255795-afd6029e-7fa1-11e8-8b5c-2918473c909b.png)

Clicking the link takes me to the file and line suggested but there is no HTML element defined at this position:
![image](https://user-images.githubusercontent.com/9105153/42255840-ede5ae72-7fa1-11e8-94f2-5401f93336c9.png)

**Comment by robbieaverill** [comment]
We stopped committing in source map files, so this could be caused by an old source map in the repo
