### ISSUE TITLE
Registries "Search results for School" grid template

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/cwp-starter-theme#9]
Features - Registries - "Search results for School table" - (Select) School link 

When using the registry module the data displays full width instead of using bootstrap grid templating.  - An example from the CWP demo site.

![image](https://user-images.githubusercontent.com/24258161/32996607-b3a8ea7c-cde9-11e7-8d19-9650610e0907.png)

**Comment by robbieaverill** [comment]
Can't reproduce with a simple registry page showing a simple one field DB model

**Comment by robbieaverill** [comment]
Feel free to reopen if this is still an issue for you @sachajudd
