### ISSUE TITLE
[3.0 + IE10/11] Checkbox label alignment is slightly out

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-starter-theme#99]
**Starter 3.0.x-dev on IE10 or IE11**

The checkbox label, for example on the login screen, is slightly out of alignment:
![image](https://user-images.githubusercontent.com/5170590/56933491-32713300-6b3c-11e9-8cf1-49b43e20f525.png)

On Chrome it looks like this:

![image](https://user-images.githubusercontent.com/5170590/56933614-c3e0a500-6b3c-11e9-85ea-aa3505e4e3bf.png)

**Comment by Cheddam** [comment]
This is an issue with Bootstrap, here's a screenshot from [the docs](https://getbootstrap.com/docs/4.3/components/forms/):

![image](https://user-images.githubusercontent.com/242621/56938723-bf75b580-6b57-11e9-8315-fba077226bfd.png)

**Comment by ScopeyNZ** [comment]
#wontfix ?
